export const baiduLangList = {
  src: [
    { name: "自动识别(不可用)", value: "auto" },
    { name: "日语", value: "jp" },
    { name: "英语", value: "en" },
    { name: "简体中文", value: "zh" },
    { name: "繁体中文", value: "cht" },
    { name: "西班牙语", value: "spa" },
    { name: "俄语", value: "ru" },
    { name: "韩语", value: "kor" },
    { name: "法语", value: "fra" },
    { name: "世界语", value: "epo" },
  ],
  dest: [
    { name: "简体中文", value: "zh" },
    { name: "繁体中文", value: "cht" },
    { name: "日语", value: "jp" },
    { name: "英语", value: "en" },
    { name: "西班牙语", value: "spa" },
    { name: "俄语", value: "ru" },
    { name: "韩语", value: "kor" },
    { name: "法语", value: "fra" },
    { name: "世界语", value: "epo" },
  ],
};

export const baiduApiLangList = {
  src: [
    { name: "自动识别", value: "auto" },
    { name: "日语", value: "jp" },
    { name: "英语", value: "en" },
    { name: "简体中文", value: "zh" },
    { name: "繁体中文", value: "cht" },
    { name: "西班牙语", value: "spa" },
    { name: "俄语", value: "ru" },
    { name: "韩语", value: "kor" },
    { name: "法语", value: "fra" },
    { name: "世界语", value: "epo" },
  ],
  dest: [
    { name: "简体中文", value: "zh" },
    { name: "繁体中文", value: "cht" },
    { name: "日语", value: "jp" },
    { name: "英语", value: "en" },
    { name: "西班牙语", value: "spa" },
    { name: "俄语", value: "ru" },
    { name: "韩语", value: "kor" },
    { name: "法语", value: "fra" },
    { name: "世界语", value: "epo" },
  ],
};

export const googleLanglist = {
  src: [
    { name: "日语", value: "ja" },
    { name: "英语", value: "en" },
    { name: "简体中文", value: "zh" },
    { name: "繁体中文", value: "zh-TW" },
    { name: "西班牙语", value: "es" },
    { name: "俄语", value: "ru" },
    { name: "韩语", value: "ko" },
    { name: "法语", value: "fr" },
    { name: "世界语", value: "eo" },
  ],
  dest: [
    { name: "简体中文", value: "zh" },
    { name: "繁体中文", value: "zh-TW" },
    { name: "日语", value: "ja" },
    { name: "英语", value: "en" },
    { name: "西班牙语", value: "es" },
    { name: "俄语", value: "ru" },
    { name: "韩语", value: "ko" },
    { name: "法语", value: "fr" },
    { name: "世界语", value: "eo" },
  ],
};
